# dodo added 44120742
"""empty message

Revision ID: 049632555b84
Revises: 4b85906e5b91
Create Date: 2023-10-05 09:35:35.005365

"""

# revision identifiers, used by Alembic.
revision = '049632555b84'
down_revision = '168cfd974dd1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('dashboard_title_RU', sa.Text(), nullable=True))
    op.add_column('slices', sa.Column('slice_name_RU', sa.Text(), nullable=True))
    op.add_column('sql_metrics', sa.Column('verbose_name_RU', sa.Text(), nullable=True))
    op.add_column('sql_metrics', sa.Column('description_RU', sa.Text(), nullable=True))
    op.add_column('table_columns', sa.Column('verbose_name_RU', sa.Text(), nullable=True))
    op.add_column('table_columns', sa.Column('description_RU', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_columns', 'description_RU')
    op.drop_column('table_columns', 'verbose_name_RU')
    op.drop_column('sql_metrics', 'description_RU')
    op.drop_column('sql_metrics', 'verbose_name_RU')
    op.drop_column('slices', 'slice_name_RU')
    op.drop_column('dashboards', 'dashboard_title_RU')
    # ### end Alembic commands ###
