# dodo added 44120742
"""empty message

Revision ID: a18f4c261e8b
Revises: 049632555b84
Create Date: 2023-11-17 11:36:09.634360

"""

# revision identifiers, used by Alembic.
revision = 'a18f4c261e8b'
down_revision = '049632555b84'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sql_metrics', sa.Column('verbose_name_EN', sa.Text(), nullable=True))
    op.add_column('sql_metrics', sa.Column('description_EN', sa.Text(), nullable=True))

    op.add_column('table_columns', sa.Column('verbose_name_EN', sa.Text(), nullable=True))
    op.add_column('table_columns', sa.Column('description_EN', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_columns', 'description_EN')
    op.drop_column('table_columns', 'verbose_name_EN')

    op.drop_column('sql_metrics', 'description_EN')
    op.drop_column('sql_metrics', 'verbose_name_EN')
    # ### end Alembic commands ###
