# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 3936ee548e9b
Revises: 8b07bae30f91
Create Date: 2023-09-12 12:48:59.581689

"""

# revision identifiers, used by Alembic.
revision = '3936ee548e9b'
down_revision = '8b07bae30f91'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slices', sa.Column('extra_lang', sa.Text(), nullable=True))
    op.add_column('slices', sa.Column('extra_lang_chart_title', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slices', 'extra_lang_chart_title')
    op.drop_column('slices', 'extra_lang')
    # ### end Alembic commands ###
