# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: b7d05f3e48f4
Revises: 049632555b84
Create Date: 2023-11-15 13:26:24.118201

"""

# revision identifiers, used by Alembic.
revision = 'b7d05f3e48f4'
down_revision = 'e09b4ae78457'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # op.drop_column('table_columns', 'description_2nd_lang')
    # op.drop_column('table_columns', 'verbose_name_2nd_lang')
    #
    # op.drop_column('sql_metrics', 'description_2nd_lang')
    # op.drop_column('sql_metrics', 'verbose_name_2nd_lang')

    op.add_column('sql_metrics', sa.Column('verbose_name_EN', sa.Text(), nullable=True))
    op.add_column('sql_metrics', sa.Column('description_EN', sa.Text(), nullable=True))
    op.add_column('sql_metrics', sa.Column('verbose_name_RU', sa.Text(), nullable=True))
    op.add_column('sql_metrics', sa.Column('description_RU', sa.Text(), nullable=True))

    op.add_column('table_columns', sa.Column('verbose_name_EN', sa.Text(), nullable=True))
    op.add_column('table_columns', sa.Column('description_EN', sa.Text(), nullable=True))
    op.add_column('table_columns', sa.Column('verbose_name_RU', sa.Text(), nullable=True))
    op.add_column('table_columns', sa.Column('description_RU', sa.Text(), nullable=True))

    op.add_column('dashboards', sa.Column('dashboard_title_RU', sa.Text(), nullable=True))
    op.add_column('slices', sa.Column('slice_name_RU', sa.Text(), nullable=True))

    op.add_column('dashboards', sa.Column('selected_lang', sa.Text(), nullable=True))
    op.add_column('dashboards',
                  sa.Column('dashboard_title_second_lang', sa.Text(), nullable=True))

    op.add_column('slices', sa.Column('extra_lang', sa.Text(), nullable=True))
    op.add_column('slices', sa.Column('slice_name_second_lang', sa.Text(), nullable=True))
    op.add_column('slices', sa.Column('primary_lang', sa.Text(), nullable=True))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_columns', 'description_EN')
    op.drop_column('table_columns', 'verbose_name_EN')
    op.drop_column('sql_metrics', 'description_EN')
    op.drop_column('sql_metrics', 'verbose_name_EN')

    op.drop_column('slices', 'primary_lang')
    op.drop_column('slices', 'slice_name_second_lang')
    op.drop_column('slices', 'extra_lang')

    op.drop_column('dashboards', 'dashboard_title_second_lang')
    op.drop_column('dashboards', 'selected_lang')
    op.drop_column('dashboards', 'dashboard_title_RU')

    op.drop_column('table_columns', 'description_RU')
    op.drop_column('table_columns', 'verbose_name_RU')
    op.drop_column('sql_metrics', 'description_RU')
    op.drop_column('sql_metrics', 'verbose_name_RU')
    op.drop_column('slices', 'slice_name_RU')

    # ### end Alembic commands ###
