# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 8b07bae30f91
Revises: e09b4ae78457
Create Date: 2023-09-06 11:25:47.634569

"""

# revision identifiers, used by Alembic.
revision = '8b07bae30f91'
down_revision = 'e09b4ae78457'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('extra_lang', sa.Text(), nullable=True))
    op.add_column('dashboards',
                  sa.Column('extra_lang_dashboard_title', sa.Text(), nullable=True))

    op.add_column('table_columns',
                  sa.Column('verbose_name_2nd_lang', sa.Text(), nullable=True))
    op.add_column('table_columns',
                  sa.Column('description_2nd_lang', sa.Text(), nullable=True))

    op.add_column('sql_metrics',
                  sa.Column('verbose_name_2nd_lang', sa.Text(), nullable=True))
    op.add_column('sql_metrics',
                  sa.Column('description_2nd_lang', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dashboards', 'extra_lang_dashboard_title')
    op.drop_column('dashboards', 'extra_lang')
    op.drop_column('table_columns', 'description_2nd_lang')
    op.drop_column('table_columns', 'verbose_name_2nd_lang')
    op.drop_column('sql_metrics', 'description_2nd_lang')
    op.drop_column('sql_metrics', 'verbose_name_2nd_lang')

    # ### end Alembic commands ###
