# dodo added 44728517
"""empty message
Revision ID: f42525e2bb55
Revises: 48cbb571fa3a
Create Date: 2024-11-02 03:50:58.181134
"""

# revision identifiers, used by Alembic.
revision = 'f42525e2bb55'
down_revision = '48cbb571fa3a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sql_metrics', sa.Column('number_format', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sql_metrics', 'number_format')
    # ### end Alembic commands ###
