# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 864745c0a17d
Revises: f42525e2bb55
Create Date: 2024-11-12 05:13:43.424865

"""

# revision identifiers, used by Alembic.
revision = '864745c0a17d'
down_revision = 'f42525e2bb55'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('filter_sets', sa.Column('user_id', sa.Integer()))
    op.add_column('filter_sets', sa.Column('isPrimary', sa.Boolean()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('filter_sets', 'user_id')
    op.drop_column('filter_sets', 'isPrimary')
    # ### end Alembic commands ###
