# dodo created 44934342
"""empty message
Revision ID: 3c0ff4a543a6
Revises: 7048393c1cd7
Create Date: 2024-08-13 16:45:42.430504
"""

# revision identifiers, used by Alembic.
revision = '3c0ff4a543a6'
down_revision = '48cbb571fa3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('logs', sa.Column('is_plugin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'is_plugin')
    # ### end Alembic commands ###
