# DODO added #32839638
"""empty message

Revision ID: dbe6e308abc8
Revises: f1ce55d13dfb
Create Date: 2024-06-06 06:33:22.208585

"""

# revision identifiers, used by Alembic.
revision = 'dbe6e308abc8'
down_revision = 'f1ce55d13dfb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('isOnboardingFinished', sa.Boolean(), nullable=True))
    op.add_column('user_info', sa.Column('onboardingStartedTime', sa.DateTime(), nullable=True))
    op.add_column('user_info', sa.Column('dodo_role', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'dodo_role')
    op.drop_column('user_info', 'onboardingStartedTime')
    op.drop_column('user_info', 'isOnboardingFinished')
    # ### end Alembic commands ###
