# DODO added #33835937
"""empty message

Revision ID: f1ce55d13dfb
Revises: 4b85906e5b91
Create Date: 2024-05-30 14:24:51.058658

"""

# revision identifiers, used by Alembic.
revision = 'f1ce55d13dfb'
down_revision = '4b85906e5b91'

from alembic import op
import logging
import sqlalchemy as sa
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()
logger = logging.getLogger("alembic.env")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(["user_id"], ["ab_user.id"]),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_info')
    # ### end Alembic commands ###
