# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: 3c0ff4a543a6
Revises: 7048393c1cd7
Create Date: 2024-08-13 16:45:42.430504

"""

# revision identifiers, used by Alembic.
revision = '3c0ff4a543a6'
down_revision = '7048393c1cd7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('data_auth_dodo', sa.Text().with_variant(mysql.MEDIUMTEXT(), 'mysql'), nullable=True))
    op.add_column('user_info', sa.Column('country_num', sa.Integer(), nullable=True))
    op.add_column('user_info', sa.Column('country_name', sa.String(), nullable=True))
    op.add_column('logs', sa.Column('is_plugin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'country_name')
    op.drop_column('user_info', 'country_num')
    op.drop_column('user_info', 'data_auth_dodo')
    op.drop_column('logs', 'is_plugin')
    # ### end Alembic commands ###
