# DODO added #32839638
"""empty message

Revision ID: 7048393c1cd7
Revises: 2c0fc74666e7
Create Date: 2024-06-18 09:46:44.733567

"""

# revision identifiers, used by Alembic.
revision = '7048393c1cd7'
down_revision = '2c0fc74666e7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('isNewTeam', sa.Boolean(), nullable=False),
    sa.Column('isExternal', sa.Boolean(), nullable=False),
    sa.Column('team_slug', sa.String(), nullable=False),
    sa.Column('created_datetime', sa.DateTime(), nullable=True),
    sa.Column('last_changed_datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ab_user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statement_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['ab_role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statements')
    # ### end Alembic commands ###
