# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""empty message

Revision ID: dbe6e308abc8
Revises: f1ce55d13dfb
Create Date: 2024-06-06 06:33:22.208585

"""

# revision identifiers, used by Alembic.
revision = 'dbe6e308abc8'
down_revision = 'f1ce55d13dfb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_info', sa.Column('isOnboardingFinished', sa.Boolean(), nullable=True))
    op.add_column('user_info', sa.Column('onboardingStartedTime', sa.DateTime(), nullable=True))
    op.add_column('user_info', sa.Column('team', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_info', 'team')
    op.drop_column('user_info', 'onboardingStartedTime')
    op.drop_column('user_info', 'isOnboardingFinished')
    # ### end Alembic commands ###
