# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
"""rename to snake_case

Revision ID: 2684073d82a4
Revises: 48cbb571fa3a
Create Date: 2025-02-14 12:54:58.589533

"""

# revision identifiers, used by Alembic.
revision = "2684073d82a4"
down_revision = "48cbb571fa3a"

from importlib import import_module  # noqa: E402

from alembic import op  # noqa: E402

module1 = import_module(
    "superset.migrations.versions.2023-07-12_20-34_e0f6f91c2055_create_user_favorite_table"
)
module2 = import_module(
    "superset.migrations.versions.2023-07-19_17-54_ee179a490af9_deckgl_path_width_units"
)


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    module1.upgrade()
    module2.upgrade()

    # Переименовываем колонки в snake_case
    op.alter_column(
        "sql_metrics",
        "verbose_name_2nd_lang",
        new_column_name="verbose_name_second_lang",
    )
    op.alter_column(
        "table_columns",
        "verbose_name_2nd_lang",
        new_column_name="verbose_name_second_lang",
    )
    op.alter_column(
        "sql_metrics",
        "description_2nd_lang",
        new_column_name="description_second_lang",
    )
    op.alter_column(
        "table_columns",
        "description_2nd_lang",
        new_column_name="description_second_lang",
    )

    op.alter_column(
        "dashboards",
        "dashboard_title_RU",
        new_column_name="dashboard_title_ru",
    )
    op.alter_column(
        "slices",
        "slice_name_RU",
        new_column_name="slice_name_ru",
    )
    op.alter_column(
        "sql_metrics",
        "verbose_name_RU",
        new_column_name="verbose_name_ru",
    )
    op.alter_column(
        "sql_metrics",
        "description_RU",
        new_column_name="description_ru",
    )
    op.alter_column(
        "table_columns",
        "verbose_name_RU",
        new_column_name="verbose_name_ru",
    )
    op.alter_column(
        "table_columns",
        "description_RU",
        new_column_name="description_ru",
    )

    op.alter_column(
        "sql_metrics",
        "verbose_name_EN",
        new_column_name="verbose_name_en",
    )
    op.alter_column(
        "sql_metrics",
        "description_EN",
        new_column_name="description_en",
    )
    op.alter_column(
        "table_columns",
        "verbose_name_EN",
        new_column_name="verbose_name_en",
    )
    op.alter_column(
        "table_columns",
        "description_EN",
        new_column_name="description_en",
    )

    op.alter_column(
        "user_info", "isOnboardingFinished", new_column_name="is_onboarding_finished"
    )
    op.alter_column(
        "user_info", "onboardingStartedTime", new_column_name="onboarding_started_time"
    )

    op.alter_column("teams", "isExternal", new_column_name="is_external")

    op.alter_column("statements", "isNewTeam", new_column_name="is_new_team")
    op.alter_column("statements", "isExternal", new_column_name="is_external")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    module2.downgrade()
    module1.downgrade()
    # ### end Alembic commands ###
